// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Proyecto_BackEnd.Context;

#nullable disable

namespace ProyectoBackEnd.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230210120901_Relaciones.cambiadas")]
    partial class Relacionescambiadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_BackEnd.Model.CajeroModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ubication")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id");

                    b.ToTable("Cashiers");
                });

            modelBuilder.Entity("Proyecto_BackEnd.Model.CallModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("cajeroid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("date")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("estado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_cajero")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("id_user")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("p2p")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("userid")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("id");

                    b.HasIndex("cajeroid");

                    b.HasIndex("userid");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Proyecto_BackEnd.Model.UserModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Proyecto_BackEnd.Model.CallModel", b =>
                {
                    b.HasOne("Proyecto_BackEnd.Model.CajeroModel", "cajero")
                        .WithMany("calls")
                        .HasForeignKey("cajeroid");

                    b.HasOne("Proyecto_BackEnd.Model.UserModel", "user")
                        .WithMany("calls")
                        .HasForeignKey("userid");

                    b.Navigation("cajero");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Proyecto_BackEnd.Model.CajeroModel", b =>
                {
                    b.Navigation("calls");
                });

            modelBuilder.Entity("Proyecto_BackEnd.Model.UserModel", b =>
                {
                    b.Navigation("calls");
                });
#pragma warning restore 612, 618
        }
    }
}
